### ISSUE TITLE
Replace melt

### ISSUE THREAD

**Issue by karthik** [karthik/CovidShinyModel#7]
```
The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant 
reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as 
well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you 
can prepend the namespace like reshape2::melt(df.to.plot). In the next version, this warning will become 
an error.
```

**Comment by karthik** [comment]
Let's leave this issue unfinished for now. I'm going to merge this back into the larger codebase so the Shiny work can continue. We can send Prs to the original repo going forward with this fix and also tests.

**Comment by karawoo** [comment]
Ok, I'm on this fix now and will submit a PR back to the original repo

**Comment by karthik** [comment]
Thanks Kara!

**Comment by karawoo** [comment]
PR opened at https://github.com/lemdt/CovidShinyModel/pull/56/, I'm going to go ahead and close this issue here
